routes/web.php
<?php
// Common
include('Common.php');

// Front End routes
include('Frontend.php');

// Backoffice routes
include('Backoffice.php');

// Webhooks
// Route::post('webhook/stripe', 'WebhookController@handleStripeCallback'); 		// Stripe
Route::post('stripe/webhook', '\Laravel\Cashier\Http\Controllers\WebhookController@handleWebhook');
// AJAX routes for get images
// Route::get('order/ajax/taxrate', 'OrderController@ajaxTaxRate')->name('ajax.taxrate');

app/SubscriptionPlan.php
<?php

namespace App;

use App\Events\Subscription\Saving;
use Illuminate\Database\Eloquent\SoftDeletes;

class SubscriptionPlan extends BaseModel
{
    use SoftDeletes;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'subscription_plans';

    /**
     * The database primary key used by the model.
     *
     * @var string
     */
    protected $primaryKey = 'plan_id';

    /**
     * The primanry key is not incrementing
     *
     * @var boolean
     */
    public $incrementing = false;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = ['deleted_at'];

    /**
     * The event map for the model.
     *
     * @var array
     */
    protected $dispatchesEvents = [
        'saving' => Saving::class,
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'deleted_at' => 'date',
        'featured' => 'boolean',
    ];

    /**
     * Get the Shops associated with the plan.
     */
    public function shops()
    {
        return $this->hasMany(Shop::class, 'current_billing_plan', 'plan_id');
    }

    /**
     * Check if the plan is the featured
     *
     * @return bool
     */
    public function isFeatured()
    {
        return $this->featured;
    }

    /**
     * Set the featured value.
     */
    public function setFeaturedAttribute($value)
    {
        $this->attributes['featured'] = (bool) $value;
    }
}

app/Http/Controllers/Admin/SubscriptionPlanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Shop;
use App\SubscriptionPlan;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Validations\CreateSubscriptionPlanRequest;
use App\Http\Requests\Validations\UpdateSubscriptionPlanRequest;

class SubscriptionPlanController extends Controller
{

    private $model;

    /**
     * construct
     */
    public function __construct()
    {
        parent::__construct();

        $this->model = trans('app.model.subscription_plan');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subscription_plans = SubscriptionPlan::withCount('shops')->orderBy('order', 'asc')->get();

        $trashes = SubscriptionPlan::onlyTrashed()->get();

        return view('admin.subscription_plan.index', compact('subscription_plans', 'trashes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.subscription_plan._create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSubscriptionPlanRequest $request)
    {
        $plan = new SubscriptionPlan;

        $plan->fill($request->all())->save();

        return back()->with('success', trans('messages.created', ['model' => $this->model]));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\SubscriptionPlan  $subscriptionPlan
     * @return \Illuminate\Http\Response
     */
    public function show(SubscriptionPlan $subscriptionPlan)
    {
        return view('admin.subscription_plan._show', compact('subscriptionPlan'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\SubscriptionPlan  $subscriptionPlan
     * @return \Illuminate\Http\Response
     */
    public function edit(SubscriptionPlan $subscriptionPlan)
    {
        return view('admin.subscription_plan._edit', compact('subscriptionPlan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubscriptionPlan  $subscriptionPlan
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSubscriptionPlanRequest $request, SubscriptionPlan $subscriptionPlan)
    {
        if( config('app.demo') == true && in_array($subscriptionPlan->plan_id, config('system.demo.plans', ['business', 'individual', 'professional'])) ) {
            return back()->with('warning', trans('messages.demo_restriction'));
        }

        try{
            \DB::beginTransaction();

            // If the plan_id changed. Update all shops that under this plan
            if($subscriptionPlan->plan_id !== $request->plan_id){
                Shop::where('current_billing_plan', $subscriptionPlan->plan_id)
                ->update(['current_billing_plan' => $request->plan_id]);
            }

            $subscriptionPlan->update($request->all());

            \DB::commit();
        }catch(\Exception $e){
            DB::rollback();
        }

        return back()->with('success', trans('messages.updated', ['model' => $this->model]));
    }

    /**
     * Trash the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\SubscriptionPlan  $subscriptionPlan
     * @return \Illuminate\Http\Response
     */
    public function trash(Request $request, SubscriptionPlan $subscriptionPlan)
    {
        if( config('app.demo') == true && in_array($subscriptionPlan->plan_id, config('system.demo.plans', ['business', 'individual', 'professional'])) ) {
            return back()->with('warning', trans('messages.demo_restriction'));
        }

        $subscriptionPlan->delete();

        return back()->with('success', trans('messages.trashed', ['model' => $this->model]));
    }

    /**
     * Restore the specified resource from soft delete.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore(Request $request,  $id)
    {
        SubscriptionPlan::onlyTrashed()->findOrFail($id)->restore();

        return back()->with('success', trans('messages.restored', ['model' => $this->model]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        SubscriptionPlan::onlyTrashed()->findOrFail($id)->forceDelete();

        return back()->with('success',  trans('messages.deleted', ['model' => $this->model]));
    }

    /**
     * Trash the mass resources.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function massTrash(Request $request)
    {
        if( config('app.demo') == true ) {
            return back()->with('warning', trans('messages.demo_restriction'));
        }

        SubscriptionPlan::whereIn('plan_id', $request->ids)->delete();

        if( $request->ajax() ) {
            return response()->json(['success' => trans('messages.trashed', ['model' => $this->model])]);
        }

        return back()->with('success', trans('messages.trashed', ['model' => $this->model]));
    }

    /**
     * Trash the mass resources.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function massRestore(Request $request)
    {
        SubscriptionPlan::onlyTrashed()->whereIn('plan_id', $request->ids)->restore();

        if( $request->ajax() ) {
            return response()->json(['success' => trans('messages.restored', ['model' => $this->model])]);
        }

        return back()->with('success', trans('messages.restored', ['model' => $this->model]));
    }

    /**
     * Trash the mass resources.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function massDestroy(Request $request)
    {
        if( config('app.demo') == true ) {
            return back()->with('warning', trans('messages.demo_restriction'));
        }

        SubscriptionPlan::withTrashed()->whereIn('plan_id', $request->ids)->forceDelete();

        if( $request->ajax() ) {
            return response()->json(['success' => trans('messages.deleted', ['model' => $this->model])]);
        }

        return back()->with('success', trans('messages.deleted', ['model' => $this->model]));
    }

    /**
     * Empty the Trash the mass resources.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function emptyTrash(Request $request)
    {
        SubscriptionPlan::onlyTrashed()->forceDelete();

        if( $request->ajax() ) {
            return response()->json(['success' => trans('messages.deleted', ['model' => $this->model])]);
        }

        return back()->with('success', trans('messages.deleted', ['model' => $this->model]));
    }

    /**
     * Save sorting order for attributes by ajax
     */
    public function reorder(Request $request)
    {
        // $this->attribute->reorder($request->all());

        foreach ($request->all() as $id => $order) {
            SubscriptionPlan::findOrFail($id)->update(['order' => $order]);
        }

        return response('success!', 200);
    }
}

resources/views/admin/subscription_plan/_create.blade.php
<div class="modal-dialog modal-md">
    <div class="modal-content">
    	{!! Form::open(['route' => 'admin.setting.subscriptionPlan.store', 'files' => true, 'id' => 'form', 'data-toggle' => 'validator']) !!}
        <div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        	{{ trans('app.form.form') }}
        </div>
        <div class="modal-body">
	        @include('admin.subscription_plan._form')
        </div>
        <div class="modal-footer">
            {!! Form::submit(trans('app.form.save'), ['class' => 'btn btn-flat btn-new']) !!}
        </div>
        {!! Form::close() !!}
    </div> <!-- / .modal-content -->
</div> <!-- / .modal-dialog -->

resources/views/admin/subscription_plan/_edit.blade.php
<div class="modal-dialog modal-md">
    <div class="modal-content">
        {!! Form::model($subscriptionPlan, ['method' => 'PUT', 'route' => ['admin.setting.subscriptionPlan.update', $subscriptionPlan->plan_id], 'files' => true, 'id' => 'form', 'data-toggle' => 'validator']) !!}
        <div class="modal-header">
        	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            {{ trans('app.form.form') }}
        </div>
        <div class="modal-body">
            @include('admin.subscription_plan._form')
        </div>
        <div class="modal-footer">
            {!! Form::submit(trans('app.update'), ['class' => 'btn btn-flat btn-new']) !!}
        </div>
        {!! Form::close() !!}
    </div> <!-- / .modal-content -->
</div> <!-- / .modal-dialog -->

resources/views/admin/subscription_plan/_form.blade.php
<div class="form-group">
  {!! Form::label('name', trans('app.form.name').'*', ['class' => 'with-help']) !!}
  <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.subscription_name') }}"></i>
  {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => trans('app.placeholder.subscription_name'), 'required']) !!}
  <div class="help-block with-errors"></div>
</div>

<div class="form-group">
  {!! Form::label('plan_id', trans('app.form.subscription_plan_id').'*', ['class' => 'with-help']) !!}
  <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.subscription_plan_id') }}"></i>
  {!! Form::text('plan_id', null, ['class' => 'form-control', 'placeholder' => trans('app.placeholder.subscription_plan_id'), 'required']) !!}
  <div class="help-block with-errors"></div>
</div>

<div class="row">
  <div class="col-md-6 nopadding-right">
    <div class="form-group">
      {!! Form::label('cost', trans('app.form.cost_per_month').'*', ['class' => 'with-help']) !!}
      <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.subscription_cost') }}"></i>
      <div class="input-group">
        <span class="input-group-addon">{{ config('system_settings.currency_symbol') ?: '$' }}</span>
        {!! Form::number('cost', null, ['class' => 'form-control', 'step' => 'any', 'placeholder' => trans('app.placeholder.subscription_cost'), 'required']) !!}
      </div>
      <div class="help-block with-errors"></div>
    </div>
  </div>
  <div class="col-md-6 nopadding-left">
    <label class="with-help">&nbsp;</label>
    <div class="form-group">
      <div class="input-group">
        {{ Form::hidden('featured', 0) }}
        {!! Form::checkbox('featured', null, null, ['id' => 'featured', 'class' => 'icheckbox_line']) !!}
        {!! Form::label('featured', trans('app.form.featured')) !!}
        <span class="input-group-addon" id="basic-addon1">
          <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.featured_subscription') }}"></i>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 nopadding-right">
    <div class="form-group">
      {!! Form::label('team_size', trans('app.form.team_size').'*', ['class' => 'with-help']) !!}
      <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.team_size') }}"></i>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-users"></i></span>
        {!! Form::number('team_size', null, ['class' => 'form-control', 'placeholder' => trans('app.placeholder.team_size'), 'required']) !!}
      </div>
      <div class="help-block with-errors"></div>
    </div>
  </div>
  <div class="col-md-6 nopadding-left">
    <div class="form-group">
      {!! Form::label('inventory_limit', trans('app.form.inventory_limit').'*', ['class' => 'with-help']) !!}
      <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.inventory_limit') }}"></i>
      <div class="input-group">
        <span class="input-group-addon"><i class="fa fa-cubes"></i></span>
        {!! Form::number('inventory_limit', null, ['class' => 'form-control', 'placeholder' => trans('app.placeholder.inventory_limit'), 'required']) !!}
      </div>
      <div class="help-block with-errors"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 nopadding-right">
    <div class="form-group">
      {!! Form::label('marketplace_commission', trans('app.form.marketplace_commission').'*', ['class' => 'with-help']) !!}
      <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.marketplace_commission') }}"></i>
      <div class="input-group">
        {!! Form::number('marketplace_commission', null, ['class' => 'form-control', 'step' => 'any', 'placeholder' => trans('app.placeholder.marketplace_commission'), 'required']) !!}
        <span class="input-group-addon">{{ trans('app.percent') }}</span>
      </div>
      <div class="help-block with-errors"></div>
    </div>
  </div>
  <div class="col-md-6 nopadding-left">
    <div class="form-group">
      {!! Form::label('transaction_fee', trans('app.form.transaction_fee').'*', ['class' => 'with-help']) !!}
      <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.transaction_fee') }}"></i>
      <div class="input-group">
        <span class="input-group-addon">{{ config('system_settings.currency_symbol') ?: '$' }}</span>
        {!! Form::number('transaction_fee', null, ['class' => 'form-control', 'step' => 'any', 'placeholder' => trans('app.placeholder.transaction_fee'), 'required']) !!}
      </div>
      <div class="help-block with-errors"></div>
    </div>
  </div>
</div>

<div class="form-group">
  {!! Form::label('best_for', trans('app.form.best_for'), ['class' => 'with-help']) !!}
  <i class="fa fa-question-circle" data-toggle="tooltip" data-placement="top" title="{{ trans('help.subscription_best_for') }}"></i>
  {!! Form::text('best_for', null, ['class' => 'form-control', 'placeholder' => trans('app.placeholder.subscription_best_for')]) !!}
</div>

<p class="help-block">* {{ trans('app.form.required_fields') }}</p>

resources/views/admin/subscription_plan/_show.blade.php
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        <div class="modal-body" style="padding: 0px;">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="position: absolute; top: 5px; right: 10px; z-index: 9;">×</button>
	  		<div class="panel panel-default">
		  		<div class="panel-body">
					<table class="table no-border">
						<tr>
							<th class="text-right">{{ trans('app.name') }}:</th>
							<td>
								<span class="lead">{{ $subscriptionPlan->name }}</span>
								@if($subscriptionPlan->featured)
									<span class="label label-primary indent10">{{ trans('app.featured') }}</span>
								@endif
							</td>
						</tr>
						<tr>
							<th class="text-right">{{ trans('app.cost') }}:</th>
							<td class="lead">{{ get_formated_currency($subscriptionPlan->cost, true, 2) . trans('app.per_month') }}</td>
						</tr>
						@if((bool) config('system_settings.trial_days'))
							<tr>
								<th class="text-right">{{ trans('app.trial_days') }}:</th>
								<td><i class="fa fa-pagelines"></i> {{ config('system_settings.trial_days') . ' ' . trans('days') }}</td>
							</tr>
						@endif
						<tr>
							<th class="text-right">{{ trans('app.team_size') }}:</th>
							<td><i class="fa fa-users"></i> {{ $subscriptionPlan->team_size }}</td>
						</tr>
						<tr>
							<th class="text-right">{{ trans('app.inventory_limit') }}:</th>
							<td><i class="fa fa-cubes"></i> {{ $subscriptionPlan->inventory_limit }}</td>
						</tr>
						<tr>
							<th class="text-right">{{ trans('app.transaction_fee') }}:</th>
							<td>{{ get_formated_currency($subscriptionPlan->transaction_fee, true, 2) }}</td>
						</tr>
						<tr>
							<th class="text-right">{{ trans('app.marketplace_commission') }}:</th>
							<td>{{ $subscriptionPlan->marketplace_commission . trans('app.percent') }}</td>
						</tr>
						<tr>
							<th class="text-right">{{ trans('app.available_from') }}:</th>
							<td>{{ $subscriptionPlan->created_at->toFormattedDateString() }}</td>
						</tr>
						<tr>
							<th class="text-right">{{ trans('app.updated_at') }}:</th>
							<td>{{ $subscriptionPlan->updated_at->toDayDateTimeString() }}</td>
						</tr>
					</table>
	        	</div>
	        </div>
        </div>
    </div> <!-- / .modal-content -->
</div> <!-- / .modal-dialog -->

resources/views/admin/subscription_plan/index.blade.php
@extends('admin.layouts.master')

@section('content')
	<div class="box">
		<div class="box-header with-border">
			<h3 class="box-title">{{ trans('app.subscription_plans') }}</h3>
			<div class="box-tools pull-right">
				@can('create', App\SubscriptionPlan::class)
					<a href="javascript:void(0)" data-link="{{ route('admin.setting.subscriptionPlan.create') }}" class="ajax-modal-btn btn btn-new btn-flat">{{ trans('app.add_subscription_plan') }}</a>
				@endcan
			</div>
		</div> <!-- /.box-header -->
		<div class="box-body">
			<table class="table table-hover table-no-option" id="sortable" data-action="{{ Route('admin.setting.subscriptionPlan.reorder') }}">
				<thead>
					<tr>
						@can('massDelete', App\SubscriptionPlan::class)
							<th class="massActionWrapper">
				                <!-- Check all button -->
								<div class="btn-group ">
									<button type="button" class="btn btn-xs btn-default checkbox-toggle">
										<i class="fa fa-square-o" data-toggle="tooltip" data-placement="top" title="{{ trans('app.select_all') }}"></i>
									</button>
									<button type="button" class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
										<span class="caret"></span>
										<span class="sr-only">{{ trans('app.toggle_dropdown') }}</span>
									</button>
									<ul class="dropdown-menu" role="menu">
										<li><a href="javascript:void(0)" data-link="{{ route('admin.setting.subscriptionPlan.massTrash') }}" class="massAction " data-doafter="reload"><i class="fa fa-trash"></i> {{ trans('app.trash') }}</a></li>
										<li><a href="javascript:void(0)" data-link="{{ route('admin.setting.subscriptionPlan.massDestroy') }}" class="massAction " data-doafter="reload"><i class="fa fa-times"></i> {{ trans('app.delete_permanently') }}</a></li>
									</ul>
								</div>
							</th>
						@endcan
				        <th width="7px">{{ trans('app.#') }}</th>
						<th>{{ trans('app.name') }}</th>
						<th><i class="fa fa-money"></i> {{ trans('app.cost_per_month') }}</th>
						<th><i class="fa fa-users"></i> {{ trans('app.team_size') }}</th>
						<th><i class="fa fa-cubes"></i> {{ trans('app.inventory_limit') }}</th>
						<th>{{ trans('app.option') }}</th>
					</tr>
				</thead>
		        <tbody id="massSelectArea">
					@foreach($subscription_plans as $subscriptionPlan )
						<tr id="{{ $subscriptionPlan->plan_id }}">
						  	@can('massDelete', App\SubscriptionPlan::class)
							  	<td>
							  		@if($subscriptionPlan->shops_count)
										<span class="text-muted">
											<i class="fa fa-ban" data-toggle="tooltip" data-placement="right" title="{{ trans('help.this_plan_has_active_subscribers') }}" ></i>
										</span>
								  	@else
										<input id="{{ $subscriptionPlan->plan_id }}" type="checkbox" class="massCheck">
								  	@endif
							  	</td>
						  	@endcan
					        <td>
								<i data-toggle="tooltip" data-placement="top" title="{{ trans('app.move') }}" class="fa fa-arrows sort-handler"> </i>
					        </td>
							<td>
								{{ $subscriptionPlan->name }}
								@if($subscriptionPlan->featured)
									<span class="label label-primary indent10">{{ trans('app.featured') }}</span>
								@endif

								<span class="label label-outline pull-right" data-toggle="tooltip" data-placement="top" title="{{ trans('help.subscribers_count') }}">
									{{ $subscriptionPlan->shops_count }}
								</span>
							</td>
							<td>{{ get_formated_currency($subscriptionPlan->cost, true, 2) }}</td>
							<td>{{ $subscriptionPlan->team_size }}</td>
							<td>{{ $subscriptionPlan->inventory_limit }}</td>
							<td class="row-options">
								@can('view', $subscriptionPlan)
									<a href="javascript:void(0)" data-link="{{ route('admin.setting.subscriptionPlan.show', $subscriptionPlan->plan_id) }}"  class="ajax-modal-btn"><i data-toggle="tooltip" data-placement="top" title="{{ trans('app.detail') }}" class="fa fa-expand"></i></a>&nbsp;
								@endcan

								@can('update', $subscriptionPlan)
									<a href="javascript:void(0)" data-link="{{ route('admin.setting.subscriptionPlan.edit', $subscriptionPlan->plan_id) }}"  class="ajax-modal-btn"><i data-toggle="tooltip" data-placement="top" title="{{ trans('app.edit') }}" class="fa fa-edit"></i></a>&nbsp;
								@endcan

								@can('delete', $subscriptionPlan)
									@if($subscriptionPlan->shops_count)
										<span class="text-muted">
											<i class="fa fa-trash-o" data-toggle="tooltip" data-placement="left" title="{{ trans('help.this_plan_has_active_subscribers') }}" ></i>
										</span>
									@else
										{!! Form::open(['route' => ['admin.setting.subscriptionPlan.trash', $subscriptionPlan->plan_id], 'method' => 'delete', 'class' => 'data-form']) !!}
											{!! Form::button('<i class="fa fa-trash-o"></i>', ['type' => 'submit', 'class' => 'confirm ajax-silent', 'title' => trans('app.trash'), 'data-toggle' => 'tooltip', 'data-placement' => 'top']) !!}
										{!! Form::close() !!}
									@endif
								@endcan
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div> <!-- /.box-body -->
	</div> <!-- /.box -->

	<div class="box collapsed-box">
		<div class="box-header with-border">
			<h3 class="box-title">
				@can('massDelete', App\SubscriptionPlan::class)
					{!! Form::open(['route' => ['admin.setting.subscriptionPlan.emptyTrash'], 'method' => 'delete', 'class' => 'data-form']) !!}
						{!! Form::button('<i class="fa fa-trash-o"></i>', ['type' => 'submit', 'class' => 'confirm btn btn-default btn-flat ajax-silent', 'title' => trans('help.empty_trash'), 'data-toggle' => 'tooltip', 'data-placement' => 'right']) !!}
					{!! Form::close() !!}
				@else
					<i class="fa fa-trash-o"></i>
				@endcan
				{{ trans('app.trash') }}
			</h3>
			<div class="box-tools pull-right">
				<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
				<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
			</div>
		</div> <!-- /.box-header -->
		<div class="box-body">
			<table class="table table-hover table-no-option">
				<thead>
					<tr>
						<th>{{ trans('app.name') }}</th>
						<th>{{ trans('app.cost_per_month') }}</th>
						<th>{{ trans('app.team_size') }}</th>
						<th>{{ trans('app.inventory_limit') }}</th>
						<th>{{ trans('app.deleted_at') }}</th>
						<th>{{ trans('app.option') }}</th>
					</tr>
				</thead>
				<tbody>
					@foreach($trashes as $trash )
					<tr>
						<td>{{ $trash->name }}</td>
						<td>{{ get_formated_currency($trash->cost, true, 2) }}</td>
						<td>{{ $trash->team_size }}</td>
						<td>{{ $trash->inventory_limit }}</td>
						<td>{{ $trash->deleted_at->diffForHumans() }}</td>
						<td class="row-options">
							@can('delete', $trash)
								<a href="{{ route('admin.setting.subscriptionPlan.restore', $trash->plan_id) }}"><i data-toggle="tooltip" data-placement="top" title="{{ trans('app.restore') }}" class="fa fa-database"></i></a>&nbsp;

								{!! Form::open(['route' => ['admin.setting.subscriptionPlan.destroy', $trash->plan_id], 'method' => 'delete', 'class' => 'data-form']) !!}
									{!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'confirm ajax-silent', 'title' => trans('app.delete_permanently'), 'data-toggle' => 'tooltip', 'data-placement' => 'top']) !!}
								{!! Form::close() !!}
							@endcan
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div> <!-- /.box-body -->
	</div> <!-- /.box -->
@endsection

@section('page-script')
	@include('plugins.drag-n-drop')
@endsection